# Generated by Django 5.2 on 2025-04-20 12:38

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(default='default/placeholder.jpg', help_text='Upload the hero section background image.', upload_to='home_page/')),
                ('about_image', models.ImageField(default='default/placeholder.jpg', help_text='Upload the about section image.', upload_to='home_page/')),
                ('hero_title', models.CharField(default='HANDCRAFTED WAX MELTS & CANDLES', help_text='Main title for the hero section.', max_length=100)),
                ('hero_subheading', models.CharField(default='A peaceful, luxury stay designed for ultimate relaxation, fun, and pampering.', help_text='Subheading text for the hero section.', max_length=255)),
                ('about_title', models.CharField(default='ABOUT US', help_text='Title for the about section.', max_length=100)),
                ('about_subheading', models.CharField(default='We take pride in producing high-quality hand-pourd wax melts and candles made from natural ingredients. Our scents are curated to create inviting and relaxing atmospheres in your home.', help_text='Subheading for the about section.', max_length=255)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy Content',
                'verbose_name_plural': 'Privacy Policy Content',
            },
        ),
        migrations.CreateModel(
            name='TermsOfServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Terms Of Service Page Content',
                'verbose_name_plural': 'Terms Of Service Page Content',
            },
        ),
    ]
