# Generated by Django 5.2 on 2025-04-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_image',
            field=models.ImageField(default='default/placeholder.png', help_text='Upload the about section image.', upload_to='home_page/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(default='default/placeholder.png', help_text='Upload the hero section background image.', upload_to='home_page/'),
        ),
    ]
