# Generated by Django 5.2 on 2025-04-22 12:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_about_image_alter_homepage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_us_page_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='This is the contents of the about us page.', null=True),
        ),
    ]
