# Generated by Django 5.2 on 2025-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_branding_facebook_link_branding_instagram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branding',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='branding',
            name='tiktok_link',
            field=models.URLField(blank=True, default='https://tiktok.com/yourcompany', help_text='Link to your TikTok profile.'),
        ),
    ]
