# Generated by Django 5.2 on 2025-04-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the candle (e.g., Lavender Scented Candle).', max_length=255)),
                ('description', models.TextField(help_text='Provide a description of the candle (e.g., A soothing lavender-scented candle).')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the price of the candle in USD (e.g., 19.99).', max_digits=10)),
                ('featured', models.BooleanField(default=False, help_text='Mark if this candle is a featured product on the site.')),
                ('best_seller', models.BooleanField(default=False, help_text='Mark if this candle is a best-seller.')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Enter the discount price if applicable, otherwise leave blank.', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaxMelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the wax melt (e.g., Vanilla Bean Wax Melt).', max_length=255)),
                ('description', models.TextField(help_text='Provide a description of the wax melt (e.g., A warm vanilla scent wax melt).')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the price of the wax melt in USD (e.g., 9.99).', max_digits=10)),
                ('featured', models.BooleanField(default=False, help_text='Mark if this wax melt is a featured product on the site.')),
                ('best_seller', models.BooleanField(default=False, help_text='Mark if this wax melt is a best-seller.')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Enter the discount price if applicable, otherwise leave blank.', max_digits=10, null=True)),
            ],
        ),
    ]
