# Generated by Django 5.2 on 2025-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('pink', 'Pink'), ('blue', 'Blue'), ('cream', 'Cream'), ('amber', 'Amber')], default=1, help_text="Choose the candle's color.", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candle',
            name='image',
            field=models.ImageField(default=1, help_text='Upload a high-quality product image.', upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candle',
            name='scent',
            field=models.CharField(choices=[('lavender', 'Lavender'), ('vanilla', 'Vanilla'), ('cinnamon', 'Cinnamon'), ('rose', 'Rose'), ('other', 'Other')], default=1, help_text="Select the candle's scent.", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candle',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default=1, help_text="Select the candle's size (small, medium, large).", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candle',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of items in stock. This controls availability.'),
        ),
        migrations.AddField(
            model_name='waxmelt',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('pink', 'Pink'), ('blue', 'Blue'), ('cream', 'Cream'), ('amber', 'Amber')], default=1, help_text='Select the color of the wax melt.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waxmelt',
            name='image',
            field=models.ImageField(default=1, help_text='Upload a clear, high-resolution image of the wax melt.', upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waxmelt',
            name='scent',
            field=models.CharField(choices=[('lavender', 'Lavender'), ('vanilla', 'Vanilla'), ('cinnamon', 'Cinnamon'), ('rose', 'Rose'), ('other', 'Other')], default=1, help_text='Choose the scent of the wax melt.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waxmelt',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default=1, help_text='Choose the size of the wax melt (e.g., Small pack, Medium, Large bundle).', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waxmelt',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total number of wax melts available in stock.'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='best_seller',
            field=models.BooleanField(default=False, help_text='Check if this is one of your top-selling candles.'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='description',
            field=models.TextField(help_text='Provide a detailed description of the candle, including scent, mood, and usage.'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter a discounted price if applicable; leave blank otherwise.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check to feature this candle on the homepage or special collections.'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the regular price in USD (e.g., 19.99).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='candle',
            name='title',
            field=models.CharField(help_text="Enter the title of the candle (e.g., 'Lavender Scented Candle').", max_length=255),
        ),
        migrations.AlterField(
            model_name='waxmelt',
            name='best_seller',
            field=models.BooleanField(default=False, help_text='Mark this wax melt as a best-seller if it’s one of your top products.'),
        ),
        migrations.AlterField(
            model_name='waxmelt',
            name='description',
            field=models.TextField(help_text='Write a description of the wax melt, including scent profile and usage suggestions.'),
        ),
        migrations.AlterField(
            model_name='waxmelt',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter a discounted price if available, or leave blank.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='waxmelt',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark this wax melt as featured to highlight it on the homepage or in promotions.'),
        ),
        migrations.AlterField(
            model_name='waxmelt',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the standard price in USD (e.g., 7.99).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='waxmelt',
            name='title',
            field=models.CharField(help_text="Enter the name of the wax melt (e.g., 'Vanilla Bean Wax Melt').", max_length=255),
        ),
    ]
