# Generated by Django 5.2 on 2025-04-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_candle_color_candle_image_candle_scent_candle_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat delivery fee applied to orders.', max_digits=6)),
                ('free_delivery_over', models.DecimalField(blank=True, decimal_places=2, help_text='Make delivery free if basket total is over this amount. Leave blank to disable.', max_digits=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Pricing Setting',
                'verbose_name_plural': 'Store Pricing Settings',
            },
        ),
    ]
